### ISSUE TITLE
Example in docs does not work (Illegal type)

### ISSUE THREAD

**Issue by listx** [expipiplus1/exact-real#16]
I am using `stack ghci` as part of my project, which has

```
extra-deps:
- exact-real-0.12.2
- memoize-0.8.1
```

in `stack.yaml`, with stack resolver 8.5 (GHC 8.0.2).

```
*Main Data.CReal> 0.5 == (1 :: CReal 0)

<interactive>:15:20: error:
    Illegal type: ‘0’ Perhaps you intended to use DataKinds
*Main Data.CReal> 0.5 * 2 == (1 :: CReal 0) * 2

<interactive>:16:24: error:
    Illegal type: ‘0’ Perhaps you intended to use DataKinds
```

**Comment by listx** [comment]
Perhaps I spoke too soon; doing `:set -XDataKinds` solves the problem.

```
*Main Data.CReal> :set -XDataKinds
*Main Data.CReal> 0.5 * 2 == (1 :: CReal 0) * 2
False
*Main Data.CReal> 0.5 == (1 :: CReal 0)
True
```

I suppose we need to mention DataKinds in the README or somewhere else.

**Comment by expipiplus1** [comment]
Fixed!

**Comment by listx** [comment]
Wow thanks, fixed in 4 minutes!

**Comment by expipiplus1** [comment]
No problem, thanks for the report.

Let me know on ~~#haskell on Freenode~~ https://matrix.to/#/#haskell:matrix.org (`@ellie:monoid.al`) if you end up doing anything cool with this package!

**Comment by SimonskiFs** [comment]
Lifesaver, thank you so much!
