### ISSUE TITLE
Alternate memoization strategy - Faster, cheaper, less pure?

### ISSUE THREAD

**Issue by Zemyla** [expipiplus1/exact-real#18]
The current memoization strategy (from the `memoize` package) really doesn't take advantage of the special structure that the fast binary Cauchy sequences have. For a normal function, calculating, for instance, `f 7` doesn't give you a way to calculate `f 3` any faster. But for Cauchy functions, if you know `f 7`, you can just round it down to get `f 3` without actually calculating the function again.

Thus, the infinite lazy binary trie is wasteful of time and memory. Instead, you can use an `MVar` holding a structure like this:

```haskell
data Cache
  = Never
  | Current {-# UNPACK #-} !Int !Integer
```

And you can either hide it in the `memoize` function you use, or keep it in the `CR` type like so:

```haskell
data CReal (n :: Nat) = CR {-# UNPACK #-} !(MVar Cache) (Int -> Integer)
```

Doing the latter allows for advantages like comparing two values for inequality potentially without even calling the associated function to the required precision - if you have two `CReal 40`s, one has cached `Current 3 (-10)` and the other has cached `Current 17 291`, then the first is obviously less than the second.

Checking the cache requires only one comparison, rather than `log n`:

```haskell
runCR :: CReal n -> Int -> Integer
runCR (CR mvc fn) !n = unsafePerformIO $ do
  vc <- takeMVar mvc
  flip onException (tryPutMVar mvc vc) $ do
    vc' <- evaluate vc
    case vc' of
      Current j v | j <= n -> do
        putMVar mvc vc'
        return $ round_down v (n - j) -- round_down is an exercise for the reader.
      _ -> let
        !v = fn n
        !vcn = Current n v
        in putMVar mvc vcn >> return v
```

The only major downside is having to use and justify `unsafePerformIO` here, and having to mark `Data.CReal.Internal` as `Trustworthy` rather than being able to infer safety. But the advantages are that it keeps data usage bounded, reduces wasteful calls, and allows prejudging comparison.

So what does everyone else here think?

**Comment by expipiplus1** [comment]
This makes a lot of sense! A PR would be very welcome!

The memoization strategy used at the moment was a "good enough"
placeholder.

On the topic of optimisation: one plan I have is to implement range
tracking (lower and upper bounds at +- infinity, one or zero), so some of
the faster, domain limited, operations can be used automatically.

Another thing to try would be to represent all computations symbolically,
when the computation needs to be evaluated determine the maximum precision
needed of all intermediates and just compute that.

**Comment by turion** [comment]
> The only major downside is having to use and justify unsafePerformIO here, and having to mark Data.CReal.Internal as Trustworthy

But this isn't trustworthy. If you want to extract a float from the same Cauchy sequence in two separate threads, you'll get side effects, right?

**Comment by Zemyla** [comment]
> > The only major downside is having to use and justify unsafePerformIO here, and having to mark Data.CReal.Internal as Trustworthy
> 
> But this isn't trustworthy. If you want to extract a float from the same Cauchy sequence in two separate threads, you'll get side effects, right?

No, because it's protected by MVars. If the first thread wants to get the value, and it's at or below what was already calculated, then it just puts it back and returns the `round_down` calculation (which won't evaluate inside the `onException` block). If it's above what was already calculated, then it will hold onto the MVar until the function given calculates the value, save it, and return it. Then, and only then, will the second thread be able to get a hold of it.

**Comment by turion** [comment]
Taking and putting MVars is blocking, this is a side effect. The execution of one thread may potentially block the execution of another thread. Plus, if there is a bug in your code it can lead to hard-to-debug concurrency issues.

I wouldn't use this module if it was hiding MVars like this.

**Comment by turion** [comment]
Instead of the `MVar` you could just use a `State` monad, and store `Cache` in there. Getting a value out of a Cauchy sequence would then be monadic.

Another option is having a closer look at `memoize` and trying to replicate their strategy. It's completely pure, but assumes lazy evaluation.

**Comment by Zemyla** [comment]
The library currently uses `memoize`. The reason I wanted to use this strategy instead is because the function evaluations aren't independent. If you know the value of `f 64`, then you know the values of `f 63` through `f 0` with very little computation required.

Actually, if the `Integer` value in `Current` isn't made strict, and neither is the evaluation in `runCR`, then the only things that happen with the `MVar` block are a case match, an `Int` comparison, and potentially a small allocation, which should be a matte of nanoseconds to resolve in total.

So now let's take a new `CReal` named `n`; its exact value matters little for this. We start two threads. One wants `runCR n 128`, and the other wants `runCR n 64`.

```
n = CR (MVar Never) fn

Thread 1 (parent) calls runCR n 128
Thread 1 (runCR) takes from MVar: vc = Never, n = CR (MVar <empty>) fn
Thread 1 (runCR) calls evaluate vc, just to make sure (even though runCR should always give it a value in WHNF), and just for illustration purposes, the runtime switches to thread 2

Thread 2 (parent) calls runCR n 64
Thread 2 (runCR) blocks on MVar, and switches back to thread 1

Thread 1 (runCR) finishes evaluate vc; vc' = Never
Thread 1 (runCR) matches on vc', and goes to the second branch. v = <thunk fn 128>, vcn = Current 128 <thunk fn 128>
Thread 1 (runCR) puts vcn in. n = CR (MVar (Current 128 <thunk fn 128>)) fn
Thread 1 (runCR) returns v = <thunk fn 128>
Thread 1 (parent) starts evaluating <thunk fn 128>, and yields during the computation. n = CR (MVar (Current 128 <partially evaluated thunk 128>)) fn

Thread 2 (runCR) takes from MVar. vc = Current 128 <partially evaluated thunk fn 128>, n = CR (MVar <empty>) fn
Thread 2 (runCR) evaluates vc; vc' = Current 128 <partially evaluated thunk fn 128>
Thread 2 (runCR) matches on vc', and goes to the first branch; v = <partially evaluated thunk fn 128>
Thread 2 (runCR) puts vc' back in; n = CR (MVar (Current 128 <partially evaluated thunk fn 128>)) fn
Thread 2 (runCR) returns round_down <partially evaluated thunk fn 128> 64
Thread 2 (parent) evaluates round_down <partially evaluated thunk fn 128> 64, and finishes it. n = CR (MVar (Current 128 <fn 128>) fn
Thread 2 (parent) yields

Thread 1 (parent) goes to continue evaluating v, and finds it's already been finished.
```

In this version, no function evaluation actually happens while the `MVar` is blocked. It winds up working like a manual version of the black-holing GHC does.

**Comment by turion** [comment]
Ideally, it would work the way you described. But the real world often isn't so lenient. What if thread 1 gets killed, as part of regular business, while evaluating? Then thread 2 is blocked indefinitely on an `MVar`. Nasty concurrency bug you wouldn't expect at all when just dealing with pure functions. Telling your users not to kill threads that evaluate cauchy sequences is a no-go. It must be safe to kill a thread performing a pure calculation.

If you want to fix this problem, you might use `STM` or some safer concurrency abstraction that allows for atomic updates. But concurrency is like crypto: Cleverer solutions usually just lead to harder-to-find bugs.

Why am I playing the devil's advocate here? One of the reasons I'm using Haskell is for safety guarantees. I want to use Cauchy sequences so I can be sure that finite float precision isn't going to bite me. I want precision guarantees to avoid nasty corner cases. I wouldn't accept nasty corner cases from concurrency as a trade-off.

**Comment by Zemyla** [comment]
> What if thread 1 gets killed, as part of regular business, while evaluating?

Then the `MVar` is put back and thread 2 gets a shot at it. That's what the `onException` is for. It catches the exception, puts back the value, and then rethrows the exception. Async exceptions are masked during the execution of the exception handler, so it can't get killed twice, and `tryPutMVar` is a non-blocking operation that doesn't allocate memory, so there's no point at which it could get killed anyway.

And a whole lot of "pure" code in Haskell uses impure functions behind the scenes for performance. The behavior of `MVar`s is well understood and documented, even inside `unsafePerformIO`. That's why I use `MVar`s instead of `STM`: `STM` operations can't be nested, and using them inside an `unsafePerformIO` block is a bad idea.

**Comment by turion** [comment]
> Cleverer solutions usually just lead to harder-to-find bugs.

I'll leave it at that. I can't find a bug in your code anymore, still I wouldn't trust it to be side-effect free in any possible situation.

 Yes, `unsafePerformIO` is used in quite a few libraries. And usually this is seen as an embarassing deficiency. I'd rather face the actual problem. As you say, for Cauchy sequences there is a cleverer memoization strategy than simply storing all values. It should be possible to implement it _purely_ as well. Maybe http://conal.net/blog/posts/elegant-memoization-with-functional-memo-tries is a good inspiration.

**Comment by turion** [comment]
Essentially, Cauchy sequences are streams. But streams can be memoized easily without using the `memoize` package. Example:

```haskell
import Debug.Trace

data Stream a = Stream a (Stream a)

getAt :: Integer -> Stream a -> a
getAt n (Stream a _) | n <= 0 = a
getAt n (Stream _ as) = getAt (n-1) as

instance Functor Stream where
  fmap f (Stream a as) = let b = f a in b `seq` Stream b $ fmap f as

instance Applicative Stream where
  pure a = Stream a $ pure a
  Stream f fs <*> Stream a as = Stream (f a) $ fs <*> as

main = do
  let s = (trace "trace" <$> pure 10 :: Stream Integer)
  print $ getAt 3 s
  print $ getAt 1 s
```
Now let's run it:
```
trace
trace
trace
trace
10
10
```
It didn't reevaluate the value at index 1. Yes, this still keep all elements of the stream in memory, so it's still not what we want. My point is just that there probably is a pure way of memoizing this.

**Comment by expipiplus1** [comment]
Implements (with @Zemyla's PR) in #21. It's such a huge speedup it's worth it imo.

@turion The only mvar functions used are `modifyMVar` and `tryTakeMVar` which shouldn't cause any nastiness.
