### ISSUE TITLE
Link to correctness proof dead

### ISSUE THREAD

**Issue by turion** [expipiplus1/exact-real#23]
The proof of correctness of the implementation is supposedly in a paper by Kornerup, but your link in the readme (http://www.imada.sdu.dk/~kornerup/RNC4/papers/p07.ps) is dead.

**Comment by expipiplus1** [comment]
Hi @turion, sorry but I can't find it online, and don't have a local copy. It would probably be best to contact Peter Kornerup and ask for a copy if you're still interested.

**Comment by expipiplus1** [comment]
I'll correct the readme
