### ISSUE TITLE
Bump stack.yaml to a more recent version?

### ISSUE THREAD

**Issue by philderbeast** [expipiplus1/exact-real#30]
The appveyor build of exact-real is failing.

https://ci.appveyor.com/project/expipiplus1/exact-real

```
In the dependencies for exact-real-0.12.2:
    QuickCheck-2.8.1 from stack configuration does not match >=2.9 && <2.10  (latest matching
                     version is 2.9.2)
needed since exact-real is a build target.
Some different approaches to resolving this:
  * Set 'allow-newer: true' in C:\sr\config.yaml to ignore all version constraints and build anyway.
  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some
    working build configuration. This can be convenient when dealing with many complicated
    constraint errors, but results may be unpredictable.
  * Recommended action: try adding the following to your extra-deps in C:\stack\stack.yaml:
QuickCheck-2.9.2@sha256:93cebf9f9c55e8a941bd3166272680d67b80d9b5d95bd836765e3d4a4ef278d0
Plan construction failed.
Command exited with code 1
```

I have a working version of stack.yaml for this project for GHC 8.2.2 but could not get it working with 7.10.2 without allowing newer dependencies. Could we bump the resolver in stack.yaml to a more recent version?

**Comment by expipiplus1** [comment]
No problem. I think I'll move CI over to github actions too.

**Comment by philderbeast** [comment]
I'm liking github actions so far. Saw this today, relevant to which versions to run with for the CI.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">A notice to everyone using Haskell with GitHub Actions: starting May 28th, we’ll only be pre-installing GHC 8.10.1, 8.8.3, and 8.6.5 on the build images. However, if you need other GHC versions, you can install them on-demand with the setup-haskell action.</p>&mdash; patrick thomson is an anagram of (@importantshock) <a href="https://twitter.com/importantshock/status/1258760576269979651?ref_src=twsrc%5Etfw">May 8, 2020</a></blockquote>

**Comment by expipiplus1** [comment]
I merged your changes so I think this can be closed.
