### ISSUE TITLE
Transitivity tests can sometimes fail

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/exact-real#35]
`cabal run test -- --quickcheck-replay=538538 -p transitive`

**Comment by cdepillabout** [comment]
Recently saw this on Hydra on x86_64-darwin: https://hydra.nixos.org/build/144127215/nixlog/1

**Comment by expipiplus1** [comment]
Released as https://hackage.haskell.org/package/exact-real-0.12.5

**Comment by expipiplus1** [comment]
@cdepillabout Thanks for the prod!
